backend:
  name: github
  repo: constructions-incongrues/pardonmyfrench-data
  branch: main
  base_url: https://decap-proxy.constructions-incongrues.net/api

media_libraries:
  stock_assets:
    providers: []

media_folder: uploads
public_folder: /uploads

editor:
  preview: false

collections:
  - name: chanson
    label: Chansons
    label_singular: Chanson
    folder: site/chansons
    path: '{{slug}}/chanson'
    format: frontmatter
    create: Contributeurs
    summary: "[{{date}}] {{contributors}} - {{title}}"
    fields:
      - { label: "Publié", name: "is_published", widget: "boolean", hint: "Les brouillons ne sont pas affichés sur le site", default: false }
      - { label: "Date de publication", name: "date", widget: "datetime", time_format: false, hint: "Date de sortie", required: true }
      - { label: "Titre", name: "title", widget: "string", hint: "Titre de la chanson" }
      - { label: "Contributeurs", name: "contributors", widget: "string", hint: "Auteurs-compositrices-interpouètes" }
      - { label: "Paroles", name: "lyrics", widget: "text", hint: "Paroles de la chanson" }
      - { label: "Audio", name: "audio", widget: "file", hint: "Le tube", accept: "audio/*" }
      - { label: "LFS OID", name: "mp3_oid", widget: "string" }
      - { label: "Titre original", name: "original_title", widget: "string" }
      - { label: "Artiste original", name: "original_artist", widget: "string" }
      - { label: "Clip original", name: "original_clip_url", widget: "string", hint: "Lien vers un clip vidéo ou audio", required: false }

    sortable_fields:
      fields: [date, title]
      default:
        field: date
        direction: descending

    view_filters:
      - label: Brouillons
        field: is_published
        pattern: false

    view_groups:
      - label: Année
        field: date
        pattern: \d{4}
      - label: Contributeurs
        field: contributors
      - label: Artiste original
        field: original_artist