backend:
  name: github
  repo: constructions-incongrues/pardonmyfrench-front
  branch: main
  base_url: https://decap-proxy.constructions-incongrues.net

media_libraries:
  stock_assets:
    providers: []

media_folder: uploads
public_folder: /uploads

editor:
  preview: false

collections:
  - name: chanson
    label: Chansons
    label_singular: Chanson
    folder: site/chansons
    path: '{{slug}}/chanson'
    format: frontmatter
    create: Contributeurs
    summary: '{{contributors}} - {{title}}'
    fields:
      - { label: Publié, name: is_published, widget: boolean, hint: Les brouillons ne sont pas affichés sur le site, default: true }
      - { label: Date de publication, name: release_date, widget: datetime, hint: Date de sortie, required: false,   time_format: false }
      - { label: ID, name: id, widget: number, hint: ID du morceau }
      - { label: Titre, name: title, widget: string, hint: Titre de la chanson }
      - { label: Contributeurs, name: contributors, widget: string, hint: Auteurs-compositrices-interpouètes }
      - { label: Paroles, name: lyrics, widget: text, hint: Paroles de la chanson }
      - { label: Audio, name: audio, widget: file, hint: Le tube, accept: audio/* }
      - { label: Titre original, name: original_title, widget: string }
      - { label: Artiste original, name: original_artist, widget: string }
      - { label: Clip original, name: original_clip_url, widget: string, hint: Lien vers un clip vidéo ou audio, required: false }

    sortable_fields:
      fields: [title, release_date, contributors, id]
      default:
        field: id
        direction: descending

    view_groups:
      - label: Année
        field: release_date
        pattern: \d{4}
      - label: Publié
        field: is_published
      - label: Contributeurs
        field: contributors
      - label: Artiste original
        field: original_artist